model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

data_params:
  type: CustomVAEDataset
  opt_dataset: 
    train:
      dataroot_gt: /home/zyyou/datasets_bk/DIV2K/DIV2K_train_HR/
    val:
      dataroot_gt: /home/zyyou/datasets_bk/DIV2K/DIV2K_valid_HR/
    train_batch_size: 8
    val_batch_size:  8
    resize: 1024
    patch_size: 64
    num_workers: 4

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
