model_params:
  name: 'VanillaVAE'
  in_channels: 3
  hidden_dims: [32, 64, 128, 256, 256, 512]
  latent_dim: 1024

data_params:
  type: CustomVAEDataset
  opt_dataset: 
    train:
      dataroot_gt: /home/zyyou/datasets_bk/DIV2K/DIV2K_train_HR/
      enlarge_ratio: 100
    val:
      dataroot_gt: /home/zyyou/datasets_bk/DIV2K/DIV2K_valid_HR/
    train_batch_size: 64
    val_batch_size:  64
    resize: 1024
    patch_size: 128
    num_workers: 4

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
