model_params:
  name: VanillaVAE
  encoder:
    type: models.encoders.resnet18
    kwargs:
      inchannels: 3
  decoder:
    type: models.decoders.resnet18
    kwargs:
      inchannels: 512
  stride: 64
  latent_dim: 2048
  patch_size: &patch_size 128

data_params:
  type: CustomVAEDataset
  opt_dataset: 
    train:
      dataroot_gt: /home/zyyou/datasets_bk/DIV2K/DIV2K_train_HR/
      enlarge_ratio: 100
    val:
      dataroot_gt: /home/zyyou/datasets_bk/DIV2K/DIV2K_valid_HR/
    train_batch_size: 32
    val_batch_size:  32
    resize: 1024
    patch_size: *patch_size
    num_workers: 32

exp_params:
  optimizer:
    type: AdamW
    kwargs:
      lr: 0.0001
      weight_decay: 0.0001
  lr_scheduler:
    type: MultiStepLR
    kwargs:
      milestones: [500, 800]
      gamma: 0.25
  kld_weight: 0.0001
  manual_seed: 1265

trainer_params:
  gpus: [0, 1, 2, 3]
  max_epochs: 1000

logging_params:
  save_dir: logs/DIV/
  name: VanillaVAE
